/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author SBS
 */
public class Livre_interface extends javax.swing.JFrame {

    public static Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public Livre_interface(Connection con) {
        this.con = con;
        initComponents();
        TableLivre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLivre = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_isbn = new javax.swing.JTextField();
        input_auteur = new javax.swing.JTextField();
        input_titre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        supp_btn = new javax.swing.JButton();
        modifier_btn = new javax.swing.JButton();
        ajout_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        input_recherche_titre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        return_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        input_exemplaire = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_recherche_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        TableLivre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableLivre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableLivre.setRowHeight(20);
        TableLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableLivreMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TableLivre);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("N° ISBN :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("TITRE :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RECHERCHER avec ID:");

        input_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_isbnActionPerformed(evt);
            }
        });

        input_auteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_auteurActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        supp_btn.setBackground(new java.awt.Color(153, 204, 255));
        supp_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supp_btn.setText("Supprimer");
        supp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_btnActionPerformed(evt);
            }
        });

        modifier_btn.setBackground(new java.awt.Color(153, 204, 255));
        modifier_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modifier_btn.setText("Modifier");
        modifier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_btnActionPerformed(evt);
            }
        });

        ajout_button.setBackground(new java.awt.Color(153, 204, 255));
        ajout_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ajout_button.setText("Ajouter");
        ajout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(supp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("AUTEUR :");

        input_recherche_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_recherche_titreActionPerformed(evt);
            }
        });
        input_recherche_titre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_recherche_titreKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Livres");

        return_btn.setText("return ");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(return_btn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(return_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("nombre exemplaire");

        input_recherche_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_recherche_idKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("RECHERCHER avec titre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                            .addComponent(input_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(input_exemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_recherche_id)
                    .addComponent(input_recherche_titre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(373, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_recherche_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_recherche_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(input_exemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1018, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_isbnActionPerformed

    private void ajout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_buttonActionPerformed
        // If the ID doesn't exist, insert the new record
        if (input_isbn.getText().isEmpty() ||input_titre.getText().isEmpty()||input_auteur.getText().isEmpty()||input_exemplaire.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "don't leave it empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (!input_exemplaire.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "number of exemplaire is a number", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            String insertQuery = "INSERT INTO livre(isbn, titre, auteur, exemplaire) VALUES (?, ?, ?, ?)";
            try (PreparedStatement pst = con.prepareStatement(insertQuery);) {
                pst.setString(1, input_isbn.getText());
                pst.setString(2, input_titre.getText());
                pst.setString(3, input_auteur.getText());
                pst.setString(4, input_exemplaire.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Enregistrement réussi");
                TableLivre();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erreur lors de l'enregistrement: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_ajout_buttonActionPerformed

    private void modifier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_btnActionPerformed
        try {
            String checkIdQuery = "SELECT COUNT(*) FROM Livre WHERE isbn = ?";
            pst = con.prepareStatement(checkIdQuery);
            pst.setString(1, input_isbn.getText());
            rs = pst.executeQuery();

            //If the ID already exists, show a warning message
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(null, "ID n'existe pas", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                // If the ID doesn't exist, insert the new record
                String insertQuery = "update livre set titre=?,auteur=?,exemplaire=? where isbn=?";
                pst = con.prepareStatement(insertQuery);
                pst.setString(1, input_titre.getText());
                pst.setString(2, input_auteur.getText());
                pst.setString(3, input_exemplaire.getText());
                pst.setString(4, input_isbn.getText());
                pst.executeUpdate();

                // Show success message and refresh the table
                JOptionPane.showMessageDialog(null, "Modification réussie");
                TableLivre();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_modifier_btnActionPerformed

    private void TableLivreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLivreMouseReleased
        int i = TableLivre.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableLivre.getModel();
        input_isbn.setText(model.getValueAt(i, 1).toString());
        input_titre.setText(model.getValueAt(i, 2).toString());
        input_auteur.setText(model.getValueAt(i, 3).toString());
        input_exemplaire.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_TableLivreMouseReleased

    private void supp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_btnActionPerformed
        try {
            String insertQuery = "delete from livre where isbn=?";
            pst = con.prepareStatement(insertQuery);
            pst.setString(1, input_isbn.getText());
            pst.executeUpdate();

            // Show success message and refresh the table
            JOptionPane.showMessageDialog(null, "Suppression réussi");
            TableLivre();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_supp_btnActionPerformed

    private void input_recherche_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_recherche_titreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_recherche_titreActionPerformed

    private void input_recherche_titreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_recherche_titreKeyReleased
        TableLivreRechercheTitre(input_recherche_titre.getText());
    }//GEN-LAST:event_input_recherche_titreKeyReleased

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
        A_principale p=new A_principale(con);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_return_btnActionPerformed

    private void input_auteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_auteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_auteurActionPerformed

    private void input_recherche_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_recherche_idKeyReleased
         TableLivreRechercheId(input_recherche_id.getText());
    }//GEN-LAST:event_input_recherche_idKeyReleased
    public void TableLivreRechercheTitre(String valeur) {
        String[] livre = {"ID","N°ISBN", "TITRE", "AUTEUR", "EXEMPLAIRE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from livre where titre like '%" + valeur + "%'";

        try {

            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_livre");
                afficher[1] = rs.getString("isbn");  // Column name must match database
                afficher[2] = rs.getString("titre");
                afficher[3] = rs.getString("auteur");
                afficher[4] = rs.getString("exemplaire");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableLivre.setModel(model);
            
            // Close the connection
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }
    public void TableLivreRechercheId(String valeur) {
        String[] livre = {"ID","N°ISBN", "TITRE", "AUTEUR", "EXEMPLAIRE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from livre where id_livre like '%" + valeur + "%'";

        try {

            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_livre");
                afficher[1] = rs.getString("isbn");  // Column name must match database
                afficher[2] = rs.getString("titre");
                afficher[3] = rs.getString("auteur");
                afficher[4] = rs.getString("exemplaire");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableLivre.setModel(model);
            
            // Close the connection
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }
    public void TableLivre() {

        String[] livre = {"ID","N°ISBN", "TITRE", "AUTEUR", "EXEMPLAIRE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from livre";

        try {
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_livre");
                afficher[1] = rs.getString("isbn");  // Column name must match database
                afficher[2] = rs.getString("titre");
                afficher[3] = rs.getString("auteur");
                afficher[4] = rs.getString("exemplaire");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableLivre.setModel(model);

            // Close the connection
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livre_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livre_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livre_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livre_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livre_interface(con).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableLivre;
    private javax.swing.JButton ajout_button;
    public javax.swing.JTextField input_auteur;
    public javax.swing.JTextField input_exemplaire;
    public javax.swing.JTextField input_isbn;
    private javax.swing.JTextField input_recherche_id;
    private javax.swing.JTextField input_recherche_titre;
    public javax.swing.JTextField input_titre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier_btn;
    private javax.swing.JButton return_btn;
    private javax.swing.JButton supp_btn;
    // End of variables declaration//GEN-END:variables

    
}
