/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SBS
 */
public class Usager_interface extends javax.swing.JFrame {

    public static Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form Usager
     */
    public Usager_interface(Connection con) {
        this.con = con;
        initComponents();
        TableUsager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        return_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        input_prenom = new javax.swing.JTextField();
        input_mail = new javax.swing.JTextField();
        input_nom = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        Supprimer_btn = new javax.swing.JButton();
        Modifier_btn = new javax.swing.JButton();
        Ajout_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUsager = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        input_rechercher_mail = new javax.swing.JTextField();
        input_role = new javax.swing.JComboBox<>();
        input_rechercher_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel16.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gestion Usagers");

        return_btn.setText("return");
        return_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(return_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(293, 293, 293))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(return_btn)
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nom : ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Prenom : ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Mail : ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Statut : ");

        input_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_prenomActionPerformed(evt);
            }
        });

        input_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_mailActionPerformed(evt);
            }
        });

        input_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nomActionPerformed(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(153, 204, 255));

        Supprimer_btn.setBackground(new java.awt.Color(153, 204, 255));
        Supprimer_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Supprimer_btn.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer_btn.setText("Supprimer");
        Supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_btnActionPerformed(evt);
            }
        });

        Modifier_btn.setBackground(new java.awt.Color(153, 204, 255));
        Modifier_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Modifier_btn.setForeground(new java.awt.Color(255, 255, 255));
        Modifier_btn.setText("Modifier");
        Modifier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_btnActionPerformed(evt);
            }
        });

        Ajout_btn.setBackground(new java.awt.Color(153, 204, 255));
        Ajout_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ajout_btn.setForeground(new java.awt.Color(255, 255, 255));
        Ajout_btn.setText("Ajouter");
        Ajout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supprimer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ajout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Ajout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Supprimer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        TableUsager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableUsager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableUsagerMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableUsager);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("RECHERCHER par mail:");

        input_rechercher_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_rechercher_mailActionPerformed(evt);
            }
        });
        input_rechercher_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_rechercher_mailKeyReleased(evt);
            }
        });

        input_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Enseignant" }));
        input_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_roleActionPerformed(evt);
            }
        });

        input_rechercher_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_rechercher_idKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("RECHERCHER par ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(input_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(input_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(input_role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(101, 101, 101)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_rechercher_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(input_rechercher_id))
                .addGap(26, 26, 26))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_rechercher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_rechercher_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_prenomActionPerformed

    private void input_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_mailActionPerformed

    private void input_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nomActionPerformed

    private void Supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_btnActionPerformed
        try {
            String enteredId = input_mail.getText();
            String checkIdQuery = "SELECT COUNT(*) FROM usager WHERE email = ?";
            pst = con.prepareStatement(checkIdQuery);
            pst.setString(1, enteredId);
            rs = pst.executeQuery();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(null, "mail n'existe pas", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                String mail = input_mail.getText();
                String Query = "SELECT COUNT(*) FROM emprunt WHERE id_usager in(select id_usager from usager where email=?)";
                pst = con.prepareStatement(Query);
                pst.setString(1, mail);
                rs = pst.executeQuery();
                if (rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(null, "se usager a des emprunt", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    String insertQuery = "delete from usager where email=?";
                    pst = con.prepareStatement(insertQuery);
                    pst.setString(1, input_mail.getText());
                    pst.executeUpdate();

                    // Show success message and refresh the table
                    JOptionPane.showMessageDialog(null, "Suppression réussi");
                    TableUsager();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Supprimer_btnActionPerformed

    private void Modifier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_btnActionPerformed

        try {

            String enteredmail = input_mail.getText();
            // Check if the mail already exists in the database
            String checkIdQuery = "SELECT COUNT(*) FROM usager WHERE email = ?";
            pst = con.prepareStatement(checkIdQuery);
            pst.setString(1, enteredmail);
            rs = pst.executeQuery();

            // If the ID already exists, show a warning message
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(null, "mail n'existe pas", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                // If the ID doesn't exist, insert the new record
                String insertQuery = "update usager set nom=?,prenom=?,role=? where email=?";
                pst = con.prepareStatement(insertQuery);
                pst.setString(1, input_nom.getText());
                pst.setString(2, input_prenom.getText());
                pst.setString(3, (String) input_role.getSelectedItem());
                pst.setString(4, input_mail.getText());
                pst.executeUpdate();

                // Show success message and refresh the table
                JOptionPane.showMessageDialog(null, "Modification réussie");
                TableUsager();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_Modifier_btnActionPerformed

    private void Ajout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajout_btnActionPerformed
        try {
            String enteredId = input_mail.getText();
            // Check if the ID already exists in the database
            String checkIdQuery = "SELECT COUNT(*) FROM usager WHERE email = ?";
            pst = con.prepareStatement(checkIdQuery);
            pst.setString(1, enteredId);
            rs = pst.executeQuery();
            if(input_nom.getText().isEmpty()||input_prenom.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "don't leave it empty", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else if (! (input_mail.getText().contains("@gmail.com") || input_mail.getText().contains("@isi-utm.tn"))) {
            JOptionPane.showMessageDialog(this, "wrong mail formate", "Error", JOptionPane.ERROR_MESSAGE);}
            else if (rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "mail deja existe", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                // If the ID doesn't exist, insert the new record
                String insertQuery = "INSERT INTO usager(nom,prenom,email,role) VALUES (?,?,?,?)";
                pst = con.prepareStatement(insertQuery);
                pst.setString(1, input_nom.getText());
                pst.setString(2, input_prenom.getText());
                pst.setString(3, input_mail.getText());
                pst.setString(4, (String) input_role.getSelectedItem());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Enregistrement réussi");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        TableUsager();
    }//GEN-LAST:event_Ajout_btnActionPerformed

    private void input_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_roleActionPerformed

    private void TableUsagerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsagerMouseReleased
        int i = TableUsager.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableUsager.getModel();
        input_nom.setText(model.getValueAt(i, 1).toString());
        input_prenom.setText(model.getValueAt(i, 2).toString());
        input_mail.setText(model.getValueAt(i, 3).toString());
        input_role.setSelectedItem(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_TableUsagerMouseReleased

    private void input_rechercher_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_rechercher_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_rechercher_mailActionPerformed

    private void input_rechercher_mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_rechercher_mailKeyReleased
        TableUsagerRechercheMail(input_rechercher_mail.getText());
    }//GEN-LAST:event_input_rechercher_mailKeyReleased

    private void return_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_btnActionPerformed
        A_principale p = new A_principale(con);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_return_btnActionPerformed

    private void input_rechercher_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_rechercher_idKeyReleased
        TableUsagerRechercheId(input_rechercher_id.getText());
    }//GEN-LAST:event_input_rechercher_idKeyReleased

    public void TableUsager() {
        String[] livre = {"ID", "NOM", "PRENOM", "MAIL", "ROLE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from usager";

        try {

            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_usager");
                afficher[1] = rs.getString("nom");  // Column name must match database
                afficher[2] = rs.getString("prenom");
                afficher[3] = rs.getString("email");
                afficher[4] = rs.getString("role");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableUsager.setModel(model);

            // Close the connection
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void TableUsagerRechercheMail(String valeur) {
        String[] livre = {"ID", "NOM", "PRENOM", "MAIL", "ROLE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from usager where email like '%" + valeur + "%'";

        try {

            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_usager");
                afficher[1] = rs.getString("nom");  // Column name must match database
                afficher[2] = rs.getString("prenom");
                afficher[3] = rs.getString("email");
                afficher[4] = rs.getString("role");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableUsager.setModel(model);

            // Close the connection
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void TableUsagerRechercheId(String valeur) {
        String[] livre = {"ID", "NOM", "PRENOM", "MAIL", "ROLE"};
        String[] afficher = new String[5];  // Changed size to 4 to match columns
        DefaultTableModel model = new DefaultTableModel(null, livre);
        String sql = "select * from usager where id_usager like '%" + valeur + "%'";

        try {

            Statement st = con.createStatement();
            rs = st.executeQuery(sql);  // Corrected to use 'st.executeQuery(sql)'

            // Iterate through the result set and populate the table
            while (rs.next()) {
                afficher[0] = rs.getString("id_usager");
                afficher[1] = rs.getString("nom");  // Column name must match database
                afficher[2] = rs.getString("prenom");
                afficher[3] = rs.getString("email");
                afficher[4] = rs.getString("role");
                model.addRow(afficher);
            }

            // Set the table model to update the UI
            TableUsager.setModel(model);

            // Close the connection
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usager_interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usager_interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usager_interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usager_interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usager_interface(con).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajout_btn;
    private javax.swing.JButton Modifier_btn;
    private javax.swing.JButton Supprimer_btn;
    private javax.swing.JTable TableUsager;
    private java.awt.Button button1;
    public javax.swing.JTextField input_mail;
    public javax.swing.JTextField input_nom;
    public javax.swing.JTextField input_prenom;
    private javax.swing.JTextField input_rechercher_id;
    private javax.swing.JTextField input_rechercher_mail;
    private javax.swing.JComboBox<String> input_role;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton return_btn;
    // End of variables declaration//GEN-END:variables
}
